project:
  type: website
  output-dir: docs

website:
  title: "Abigail's Data Visualization Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/abigailwsmith
format:
  html:
    theme: journal
    css: styles.css



